project:
  type: website
  output-dir: docs   # GitHub Pages가 읽을 폴더

website:
  title: "Master Thesis Literature Review"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Posts
        menu:
          - href: posts/index.qmd
            text: All posts

format:
  html:
    theme: cosmo     # 마음대로 바꿔도 됨
    toc: true
